version: "3.7"
services:
  main:
    # Dockerfile で build
    build: .

    # .env から環境変数をコンテナへ渡す
    environment:
      - TZ=Asia/Tokyo
      - BOT_TOKEN
      - DATABASE_URL

    # ホスト側ディレクトリとコンテナをマウント
    volumes:
      - ./discordbot-mdn/:/discordbot-mdn/

    # 実行するコマンドの指定
    command: python3 -u bot.py # -u: Python のログを表示する
