version: "3.7"
services:

  db:
    image: postgres:14.5-alpine3.16
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d # 初期設定用ディレクトリのバインドマウント。ビルド時に init.sql を実行してテーブル作成などの初期設定を行う
      - db-volume:/var/lib/postgresql/data          # 名前付きデータボリュームへ PSQL のデータが保存されているディレクトリをマウント。DB 上のデータを永続化する
    ports:
      - 55432:5432
    environment:
      - LANG=ja_JP.utf8
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - TZ=Asia/Tokyo
    restart: always

  main:
    build: .
    environment:
      - BOT_TOKEN
      - DATABASE_URL
      - TZ=Asia/Tokyo
    volumes:
      - ./discordbot-mdn/:/discordbot-mdn/ # bot のソースコードをバインドマウント
    restart: always

volumes:
  db-volume:
