version: "3.7"
services:
  my_app:
    # CD にある Dockerfile で build
    build:
      context: .
      dockerfile: Dockerfile
      # .env から環境変数を Dockerfile へ渡す
      args:
        TZ: $TZ
        BOT_TOKEN: $BOT_TOKEN

    # .env から環境変数をコンテナへ渡す
    environment:
      TZ: $TZ
      BOT_TOKEN: $BOT_TOKEN

    # image と実行するコマンドの指定
    image: discordbot-mdn
    command: python3 -u mdn.py # -u: Python のログを表示する